/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 17 21:45:17 GMT 2017
 */

package org.cs362.dominion;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.cs362.dominion.Card;
import org.cs362.dominion.SupplyStack;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SupplyStack_ESTest extends SupplyStack_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SupplyStack supplyStack0 = new SupplyStack("", 0);
      Card card0 = supplyStack0.type;
      card0.worth = 213;
      int int0 = supplyStack0.hasTreasure();
      assertEquals(213, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SupplyStack supplyStack0 = new SupplyStack("", 1199);
      Card card0 = supplyStack0.type;
      card0.worth = (-1);
      int int0 = supplyStack0.hasTreasure();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SupplyStack supplyStack0 = new SupplyStack("", (-1));
      Card card0 = new Card("Xv<cSyHoEMkCrB<8CL+");
      card0.cardType = null;
      supplyStack0.type = card0;
      String string0 = supplyStack0.getType();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SupplyStack supplyStack0 = new SupplyStack("", 1199);
      Card card0 = supplyStack0.type;
      card0.cardType = "vLu]9^<t?,TaM";
      String string0 = supplyStack0.getType();
      assertEquals("vLu]9^<t?,TaM", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SupplyStack supplyStack0 = new SupplyStack("d}UK:+|x--\"9&%7}X/[", 0);
      supplyStack0.type = null;
      // Undeclared exception!
      try { 
        supplyStack0.hasTreasure();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.cs362.dominion.SupplyStack", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SupplyStack supplyStack0 = new SupplyStack("", 3211);
      supplyStack0.type = null;
      // Undeclared exception!
      try { 
        supplyStack0.getType();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.cs362.dominion.SupplyStack", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      SupplyStack supplyStack0 = null;
      try {
        supplyStack0 = new SupplyStack((String) null, 1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.cs362.dominion.Card", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      SupplyStack supplyStack0 = new SupplyStack("", 1199);
      String string0 = supplyStack0.getType();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      SupplyStack supplyStack0 = new SupplyStack("", 1199);
      int int0 = supplyStack0.hasTreasure();
      assertEquals(0, int0);
  }
}
